### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bugerry87** [restorecommerce/rendering-srv#6]
# Environment

rendering-srv

- Ubuntu 20.04 LTS
- NPM 7.7.6
- NodeJS v14.16.0

# What was done

- Backing System is running (only!)
- Packages installed `npm install`
- Executed pretest `npm run pretest`
- Executed test `npm run test`

# Results

```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
```

# Error Snippits

```
SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module.replacementCompile (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gerald/nfuse/restorecommerce/rendering-srv/test/test.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.replacementCompile (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/gerald/nfuse/restorecommerce/rendering-srv/node_modules/yargs/build/index.cjs:443:71
```

**Comment by Arun-KumarH** [comment]
Runs fine locally:
```
 rendering srv testing
Supervisor uses configuration file: /home/akumar/github/rendering-srv/test/cfg/config_test.json
Supervisor uses configuration file: /home/akumar/github/rendering-srv/test/cfg/config.json
(node:3617) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Method handler command for /io.restorecommerce.commandinterface.Service/Command expected but not provided
    with test response listener
      ✓ should return missing payload response if request payload is empty (51ms)
      ✓ should render a plain template with no layouts or styles (201ms)
      ✓ should render a template using custom helper "list"
      ✓ should render with layout
      ✓ should render with external stylesheet (48ms)
      ✓ should render without css for missing stylesheet (99ms)
      ✓ should render multiple templates (40ms)
      ✓ Should render CSS inline on complex template (362ms)


  8 passing (1s)

-----------------|---------|----------|---------|---------|--------------------------------------------------------------------------------
File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------|---------|----------|---------|---------|--------------------------------------------------------------------------------
All files        |   81.14 |    69.84 |   85.29 |   82.14 |
 handlebars      |     100 |      100 |     100 |     100 |
  helper-list.js |     100 |      100 |     100 |     100 |
 lib             |   80.59 |    69.84 |   83.87 |   81.71 |
  service.js     |   80.59 |    69.84 |   83.87 |   81.71 | 85,118,125-126,129-130,142-143,147,161,175,182-184,187-191,208,253-254,269-277
-----------------|---------|----------|---------|---------|--------------------------------------------------------------------------------
```

https://github.com/restorecommerce/rendering-srv/runs/2149461573
Even on GH workflows tests have passed, can you pls recheck this again ?
